function generate_information_dialog(title,string,varargin)
UI = struct(...
    'Margin',30,... %[px]
    'ButtonBarHeight', 100,... %[px]
    'ButtonWidth', 200,...
    'ButtonHeight', 50,...
    'IconSize',100,... %[px]
    'FontUnits','points',...
    'FontName','FixedWidth',...
    'FontAngle','normal',...
    'FontSize',20,...
    'FontWeight','normal');

objInputParser = inputParser;
addParamValue(objInputParser,...
    'FontUnits', UI.FontUnits, @(x)isnumeric(x));
addParamValue(objInputParser,...
    'FontName', UI.FontName, @(x)ischar(x));
addParamValue(objInputParser,...
    'FontAngle', UI.FontAngle, @(x)ischar(x));
addParamValue(objInputParser,...
    'FontSize', UI.FontSize, @(x)isnumeric(x));
addParamValue(objInputParser,...
    'FontWeight', UI.FontWeight, @(x)ischar(x));
addParamValue(objInputParser,...
    'IsModal', true, @(x)islogical(x));
addParamValue(objInputParser,...
    'PauseQueue', true, @(x)islogical(x));
parse(objInputParser,varargin{:});
inputs = objInputParser.Results;

if iscell(string)
    numString = numel(string);
    [stringWidth,stringHeight] = deal(zeros(numString,1));
    for idxString = 1:numString
        [stringWidth(idxString),stringHeight(idxString)] = ...
            get_text_extent(string{idxString},varargin{:});
    end %for
else
    numString = 1;
    [stringWidth,stringHeight] = ...
        get_text_extent(string,varargin{:});
end %for
scrSize = get(0, 'ScreenSize');
%             if max(stringExtent) > scrSize(3)
%                 %cut string
%             end %if

axWidth = max(stringWidth)+2*UI.Margin;
figWidth = axWidth+UI.IconSize;
axHeight = sum(stringHeight)+2*UI.Margin;
figHeight = axHeight+UI.ButtonBarHeight;
UI.hFig =...
    figure(...
    'Units','pixels',...
    'Position',[0.5*(scrSize(3)-figWidth),0.5*(scrSize(4)-figHeight),figWidth,figHeight],...
    'Name', title,...
    'NumberTitle', 'off',...
    'MenuBar', 'none',...
    'ToolBar', 'none',...
    'DockControls', 'off',...
    'Resize', 'off',...
    'IntegerHandle','off',...
    'Color', [1 1 1],...
    'Visible','off');
if inputs.IsModal
    set(UI.hFig,...
        'WindowStyle','modal')
end %if

hAx = axes(...
    'Parent',UI.hFig,...
    'Units','pixels',...
    'Position',[UI.Margin+UI.IconSize+1,UI.ButtonBarHeight+1,...
    axWidth,axHeight],...
    'Visible','off');

y0 = linspace(0,axHeight,numString+2);
y0 = y0(end-1:-1:2);
for idxString = 1:numString
    text(0,y0(idxString),...
        string{idxString},...
        'Parent',hAx,...
        'Units','pixels',...
        'HorizontalAlignment','left',...
        'VerticalAlignment','middle',...
        'FontUnits',inputs.FontUnits,...
        'FontName',inputs.FontName,...
        'FontAngle',inputs.FontAngle,...
        'FontSize',inputs.FontSize,...
        'FontWeight',inputs.FontWeight)
end %for

hAx = axes(...
    'Parent',UI.hFig,...
    'Units','pixels',...
    'Position',[1,UI.ButtonBarHeight+1,UI.IconSize,axHeight],...
    'Visible','off');
icon = load('dialogicons.mat');
imshow(icon.lightbulbIconData,icon.lightbulbIconMap,'Parent',hAx)

uicontrol(...
    'Parent', UI.hFig,...
    'Style', 'pushbutton',...
    'Units','pixels',...
    'Position', [figWidth-UI.ButtonWidth-UI.Margin,...
    (UI.ButtonBarHeight-UI.ButtonHeight)/2,...
    UI.ButtonWidth,UI.ButtonHeight],...
    'FontUnits',inputs.FontUnits,...
    'FontName',inputs.FontName,...
    'FontAngle',inputs.FontAngle,...
    'FontSize',inputs.FontSize,...
    'FontWeight',inputs.FontWeight,...
    'String', 'OK',...
    'Callback','close(gcf)');

set(UI.hFig,...
    'Visible','on');
if inputs.PauseQueue
    uiwait(UI.hFig)
end %if
end %fun