classdef CoverslideScanner < handle
    %written by
    %C.P.Richter
    %Division of Biophysics / Group J.Piehler
    %University of Osnabrueck
    
    %% v1:BUG fixing
    
    properties(Transient)
        WorkPath
        
        hFig
        
        NAVI = struct(...
            'hRoi',[])
        BAR
        
        GUI
        
        Acq = struct(...
            'ScanSize',10,...
            'LaserWvlnth',405) %[nm]
        
        Analysis = struct([]);
        
        MICMAN
    end %properties
    
    methods
        %constructor
        function this = CoverslideScanner
            warning('off','MATLAB:nargchk:deprecated')
            
            this.WorkPath = pwd;
            addpath(genpath(this.WorkPath))
            
            this.MICMAN = classMicroManagerWrapper;
            
            this.Acq.LiveViewTimer = timer(...
                'BusyMode','drop',...
                'ExecutionMode','fixedSpacing',...
                'Period',0.06,...
                'StartFcn',@(src,evnt)start_live_view(this),...
                'TimerFcn',@(src,evnt)update_live_view(this),...
                'StopFcn',@(src,evnt)stop_live_view(this));
            
            figPos = set_figure_position(1.618,0.6,'center');
            this.hFig = figure(...
                'Units','pixels',...
                'Name','Coverslide Scanner (Version: 1)',...
                'NumberTitle', 'off',...
                'DockControls', 'off',...
                'MenuBar','none',...
                'Toolbar','none',...
                'Color','w',...
                'KeyPressFcn',@(src,evnt)proc_keyboard(this,evnt),...
                'Position',figPos-[0 0 10 10],...
                'IntegerHandle','off',...
                'Visible','on');
            
            %--------------------------------------------------------------
            
            this.GUI.hTabGrp = uitabgroup(this.hFig,...
                'Parent', this.hFig,...
                'Units','normalized',...
                'Position',[0 0 2/3 1],...
                'SelectionChangedFcn',@(src,evnt)set_tab(this,evnt));
            
            %--------------------------------------------------------------
            
            tab = uitab(this.GUI.hTabGrp,...
                'BackgroundColor','w',...
                'Title','Profile');
            
            this.GUI.hAxProfile = axes(...
                'Parent',tab,...
                'Units','normalized',...
                'OuterPosition', [0 0.2 1 0.8],...
                'Box','on');
            
            [~,temp] = dos('getmac');
            
            if( length(temp) > 240 && strcmp( temp(239:255), '08-62-66-B8-34-DD' ) )
                img = zeros( 600,600 );
            else
                img = imread('\\wsvbp\bp-matlab-tools$\CoverslideScanner\Setup.png');
            end
            imagesc(img,...
                'Parent',this.GUI.hAxProfile)
            
            this.GUI.hPushSwitchProfile = uicontrol(...
                'Parent', tab,...
                'Style', 'pushbutton',...
                'Units','normalized',...
                'Position', [0,0,0.15,0.05],...
                'String', sprintf('Profile:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor','w',...
                'HorizontalAlignment', 'center',...
                'Callback', @(src,evnt)load_profile(this));
            
            profile = fullfile(this.MICMAN.MicManPath,this.MICMAN.Profile);
            if not(exist(profile,'file')==2)
                profile = '';
            end %if
            
            this.GUI.hEditProfile = uicontrol(...
                'Parent', tab,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [0.15,0,0.6,0.05],...
                'String', profile,...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor','w',...
                'HorizontalAlignment', 'center');
            
            this.GUI.hToggleInitMM = uicontrol(...
                'Parent', tab,...
                'Style', 'togglebutton',...
                'Units','normalized',...
                'Position', [0.75,0,0.25,0.05],...
                'String', 'Initialize µManager',...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',[1 0.5 0.5],...
                'HorizontalAlignment', 'center',...
                'Callback', @(src,evnt)initialize_micro_manager(this,src));
            
            axis(this.GUI.hAxProfile,'image','ij','off')
            
            %--------------------------------------------------------------
            
            tab = uitab(this.GUI.hTabGrp,...
                'BackgroundColor','w',...
                'Title','Coverslide Scan');
            
            this.GUI.hAxFocus = axes(...
                'Parent',tab,...
                'Units','normalized',...
                'OuterPosition', [0 0 1 1],...
                'Box','on');
            
            this.GUI.hImgFocus = imagesc(...
                'xdata',[],'ydata',[],'cdata',[],...
                'Parent',this.GUI.hAxFocus);
            
            this.GUI.hLineScanPath = line(...
                'Parent',this.GUI.hAxFocus,...
                'xdata',[],'ydata',[],...
                'color','r',...
                'marker','.',...
                'markersize',20,...
                'linewidth',2,...
                'linestyle','-');
            
            xlabel(this.GUI.hAxFocus,'x-x_0 [µm]')
            ylabel(this.GUI.hAxFocus,'y-y_0 [µm]')
            
            colormap(this.GUI.hAxFocus,gray(256))
            axis(this.GUI.hAxFocus,'image','xy')
            
            %--------------------------------------------------------------
            
            tab = uitab(this.GUI.hTabGrp,...
                'BackgroundColor','w',...
                'Title','Live View');
            
            this.GUI.hAxLive = axes(...
                'Parent',tab,...
                'Units','normalized',...
                'OuterPosition', [0 0 1 1],...
                'Box','on');
            
            this.GUI.hImgLive = imagesc(...
                'xdata',[],'ydata',[],'cdata',[],...
                'Parent',this.GUI.hAxLive);
            
            xlabel(this.GUI.hAxLive,'x-position')
            ylabel(this.GUI.hAxLive,'y-position')
            
            colormap(this.GUI.hAxLive,gray(256))
            axis(this.GUI.hAxLive,'image','ij')
            
            %--------------------------------------------------------------
            
            hPanel = uipanel(...
                'Parent', this.hFig,...
                'Units','normalized',...
                'backgroundcolor','w',...
                'Position',[2/3 0.05 1/3 0.95]);
            
            objMasterPanel = classMasterPanel(this);
            
            objPanelSel = add_param_panel(objMasterPanel,'MainPanelHeight',1,...
                'Title','Navigation','IsExpandable',true,'IsExpanded',false);
            objPanelNavSpace = add_param_subpanel(objPanelSel,'MainPanelHeight',450);
            
            objPanelAcq = add_param_panel(objMasterPanel,'MainPanelHeight',1,...
                'Title','Acquisition','IsExpandable',true,'IsExpanded',true);
            objPanelImgSize = add_param_subpanel(objPanelAcq,'MainPanelHeight',80,'IsExpandable',true);
            objPanelCamIlluArea = add_param_subpanel(objPanelImgSize,'MainPanelHeight',450);
            objPanelScanSize = add_param_subpanel(objPanelAcq,'MainPanelHeight',80);
            objPanelExpTime = add_param_subpanel(objPanelAcq,'MainPanelHeight',80);
            objPanelAcqMode = add_param_subpanel(objPanelAcq,'MainPanelHeight',40);
            objPanelCleanupFilterButton = add_param_subpanel(objPanelAcq,'MainPanelHeight',40);
            
            objPanelDIC = add_param_subpanel(objPanelAcq,'MainPanelHeight',1,...
                'Title','DIC Settings','IsExpandable',true);
            objPanelLampVoltage = add_param_subpanel(objPanelDIC,'MainPanelHeight',80);
            objPanelDicFlatField = add_param_subpanel(objPanelDIC,'MainPanelHeight',40,'IsExpandable',true);
            objPanelDicBg = add_param_subpanel(objPanelDicFlatField,'MainPanelHeight',450);
            objPanelDicBgSample = add_param_subpanel(objPanelDicFlatField,'MainPanelHeight',40);
            
            objPanelFluor = add_param_subpanel(objPanelAcq,'MainPanelHeight',1,...
                'Title','Fluorescense Settings','IsExpandable',true,'IsExpanded',false);
            objPanelLaserLine = add_param_subpanel(objPanelFluor,'MainPanelHeight',40);
            objPanelLaserPowerButton = add_param_subpanel(objPanelFluor,'MainPanelHeight',40);
            objPanelLaserAttenuation = add_param_subpanel(objPanelFluor,'MainPanelHeight',80);
            
            objPanelZDC = add_param_subpanel(objPanelAcq,'MainPanelHeight',1,...
                'Title','Auto-Focus','IsExpandable',true,'IsExpanded',false);
            objPanelZdcSearchRange = add_param_subpanel(objPanelZDC,'MainPanelHeight',80);
            objPanelZdcOffset = add_param_subpanel(objPanelZDC,'MainPanelHeight',80);
            objPanelZdcLock = add_param_subpanel(objPanelZDC,'MainPanelHeight',40);
            
            objPanelScan = add_param_panel(objMasterPanel,'MainPanelHeight',40);
            
            initialize_param_ui(objMasterPanel,hPanel)
            finalize_param_ui(objMasterPanel)
            
            %--------------------------------------------------------------
            this.GUI.NAVI.hAx = axes(...
                'Parent',objPanelNavSpace.hMainPanel,...
                'Units','normalized',...
                'OuterPosition', [0 0 1 1],...
                'Box','on');
            
            this.GUI.NAVI.hImg = imagesc(...
                'xdata',[],'ydata',[],'cdata',[],...
                'Parent',this.GUI.NAVI.hAx);
            
            xlabel(this.GUI.NAVI.hAx,'x-position')
            ylabel(this.GUI.NAVI.hAx,'y-position')
            
            colormap(this.GUI.NAVI.hAx,gray(256))
            
            axis(this.GUI.NAVI.hAx,'xy','image')
            
            this.NAVI.hRoi = imrect(this.GUI.NAVI.hAx,[0 0 1 1]);
            hList = get(this.NAVI.hRoi,'Children');
            set(hList([5 7 9 11]),...
                'LineWidth',3,...
                'LineStyle','-',...
                'Color','m')
            set(hList([1:4 6 8 10 12]),...
                'MarkerSize',10,...
                'MarkerFaceColor', 'm',...
                'MarkerEdgeColor', 'm')
            set(hList([14 15]),...
                'LineStyle','none')
            set(hList(13),...
                'UIContextMenu',[])
            addNewPositionCallback(this.NAVI.hRoi,@(pos)update_navi_focus(this,pos));
            
            %--------------------------------------------------------------
            uicontrol(...
                'Parent', objPanelImgSize.hMainPanel,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0,0.5,1,0.5],...
                'String', sprintf('Image Size [px]:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',objPanelImgSize.BackgroundColor,...
                'HorizontalAlignment', 'center');
            this.GUI.hSliderImgSize = uicontrol(...
                'Parent', objPanelImgSize.hMainPanel,...
                'Style', 'slider',...
                'Min',2,...
                'Max',2048,...
                'SliderStep',[2 50]/(2048-2),...
                'Units', 'normalized',...
                'Position', [0,0,0.75,0.5],...
                'Enable','off');
            addlistener(this.GUI.hSliderImgSize,'ContinuousValueChange',...
                @(src,event)set_img_size(this,src));
            this.GUI.hEditImgSize = uicontrol(...
                'Parent', objPanelImgSize.hMainPanel,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [0.75,0,0.25,0.5],...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Callback', @(src,evnt)set_img_size(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            this.GUI.hAxCamIlluArea = axes(...
                'Parent',objPanelCamIlluArea.hMainPanel,...
                'Units','normalized',...
                'OuterPosition', [0 0 1 1],...
                'Box','on');
            
            this.GUI.hImgCamIlluArea = imagesc(...
                'xdata',[],'ydata',[],'cdata',[],...
                'Parent',this.GUI.hAxCamIlluArea);
            
            title(this.GUI.hAxCamIlluArea,'Camera Chip Illuminated Area')
            
            colormap(this.GUI.hAxCamIlluArea,[0 0 0; 1 1 0])
            
            axis(this.GUI.hAxCamIlluArea,'ij','image','off')
            
            %--------------------------------------------------------------
            uicontrol(...
                'Parent', objPanelScanSize.hMainPanel,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0,0.5,1,0.5],...
                'String', sprintf('Scan Size:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',objPanelScanSize.BackgroundColor,...
                'HorizontalAlignment', 'center');
            this.GUI.hSliderScanSize = uicontrol(...
                'Parent', objPanelScanSize.hMainPanel,...
                'Style', 'slider',...
                'Min',1,...
                'Max',20,...
                'SliderStep',[1 3]/(20-1),...
                'Value', 10,...
                'Units', 'normalized',...
                'Position', [0,0,0.75,0.5],...
                'Enable','off');
            addlistener(this.GUI.hSliderScanSize,'ContinuousValueChange',...
                @(src,event)set_scan_size(this,src));
            this.GUI.hEditScanSize = uicontrol(...
                'Parent', objPanelScanSize.hMainPanel,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [0.75,0,0.25,0.5],...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'String', 10,...
                'Callback', @(src,evnt)set_scan_size(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            uicontrol(...
                'Parent', objPanelExpTime.hMainPanel,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0,0.5,1,0.5],...
                'String', sprintf('Exposure Time [ms]:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',objPanelExpTime.BackgroundColor,...
                'HorizontalAlignment', 'center');
            this.GUI.hSliderExpTime = uicontrol(...
                'Parent', objPanelExpTime.hMainPanel,...
                'Style', 'slider',...
                'Min',0,...
                'Max',1000,...
                'SliderStep',[1 10]/1000,...
                'Units', 'normalized',...
                'Position', [0,0,0.75,0.5],...
                'Enable','off');
            addlistener(this.GUI.hSliderExpTime,'ContinuousValueChange',...
                @(src,event)set_exp_time(this,src));
            this.GUI.hEditExpTime = uicontrol(...
                'Parent', objPanelExpTime.hMainPanel,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [0.75,0,0.25,0.5],...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Callback', @(src,evnt)set_exp_time(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            uicontrol(...
                'Parent', objPanelAcqMode.hMainPanel,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0,0,0.5,1],...
                'String', sprintf('Acquisition Mode:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',objPanelAcqMode.BackgroundColor,...
                'HorizontalAlignment', 'center');
            
            this.GUI.hDropAcqMode = uicontrol_popupmenu_wrapper(...
                'Parent',objPanelAcqMode.hMainPanel,...
                'Units','normalized',...
                'Position', [0.5 0 0.5 1],...
                'FontUnits','normalized',...
                'String',{'DIC','Fluorescense'},...
                'Value',1,...
                'Enable','off');
            
            %--------------------------------------------------------------
            this.GUI.hToggleCleanupFilterButton = uicontrol(...
                'Parent',objPanelCleanupFilterButton.hMainPanel,...
                'Style', 'pushbutton',...
                'Units','normalized',...
                'Position', [0,0,1,1],...
                'FontUnits','normalized',...
                'FontSize', 0.5,...
                'String', 'Calibrate CellSens Cleanup Filter Button',...
                'BackgroundColor',[1 0.5 0.5],...
                'Callback', @(src,evnt)set_pos_cleanup_filter_button(this),...
                'Enable','off');
            
            %--------------------------------------------------------------
            uicontrol(...
                'Parent', objPanelLampVoltage.hMainPanel,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0,0.5,1,0.5],...
                'String', sprintf('Lamp Intensity [Volt]:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',objPanelLampVoltage.BackgroundColor,...
                'HorizontalAlignment', 'center');
            this.GUI.hSliderLampVoltage = uicontrol(...
                'Parent', objPanelLampVoltage.hMainPanel,...
                'Style', 'slider',...
                'Min',0,...
                'Max',12,...
                'SliderStep',[0.1 0.5]/12,...
                'Units', 'normalized',...
                'Position', [0,0,0.75,0.5],...
                'Enable','off');
            addlistener(this.GUI.hSliderLampVoltage,'ContinuousValueChange',...
                @(src,event)set_dic_lamp_voltage(this,src));
            this.GUI.hEditLampVoltage = uicontrol(...
                'Parent', objPanelLampVoltage.hMainPanel,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [0.75,0,0.25,0.5],...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Callback', @(src,evnt)set_dic_lamp_voltage(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            this.GUI.hCheckFlatFieldCorr = uicontrol(...
                'Parent',objPanelDicFlatField.hMainPanel,...
                'Style', 'checkbox',...
                'Units','normalized',...
                'Position', [0.05,0,1,1],...
                'FontUnits','normalized',...
                'FontSize', 0.5,...
                'String', ' Apply Flat-Field Correction',...
                'Backgroundcolor',objPanelDicFlatField.BackgroundColor,...
                'Enable','off');
            
            %--------------------------------------------------------------
            this.GUI.hAxDicBg = axes(...
                'Parent',objPanelDicBg.hMainPanel,...
                'Units','normalized',...
                'OuterPosition', [0 0 1 1],...
                'Box','on');
            
            this.GUI.hImgDicBg = imagesc(...
                'xdata',[],'ydata',[],'cdata',[],...
                'Parent',this.GUI.hAxDicBg);
            
            colormap(this.GUI.hAxDicBg,gray(256))    
            
            axis(this.GUI.hAxDicBg,'xy','image','off')
            
            %--------------------------------------------------------------
            this.GUI.hPushDicBgSample = uicontrol(...
                'Parent',objPanelDicBgSample.hMainPanel,...
                'Style', 'togglebutton',...
                'Units','normalized',...
                'Position', [0,0,1,1],...
                'FontUnits','normalized',...
                'FontSize', 0.5,...
                'String', 'Sample Background',...
                'Callback', @(src,evnt)get_dic_bg(this),...
                'Enable','off');
            
            %--------------------------------------------------------------
            uicontrol(...
                'Parent', objPanelLaserLine.hMainPanel,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0,0,0.5,1],...
                'String', sprintf('Laser Wavelength [nm]:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',objPanelLaserLine.BackgroundColor,...
                'HorizontalAlignment', 'center');
            
            this.GUI.hDropLaserWvlnth = uicontrol_popupmenu_wrapper(...
                'Parent',objPanelLaserLine.hMainPanel,...
                'Units','normalized',...
                'Position', [0.5 0 0.5 1],...
                'FontUnits','normalized',...
                'String',{'405','488','561','640'},...
                'Value',1,...
                'Callback', @(src,evnt)set_fluor_laser_line(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            this.GUI.hToggleLaserPowerButton = uicontrol(...
                'Parent',objPanelLaserPowerButton.hMainPanel,...
                'Style', 'pushbutton',...
                'Units','normalized',...
                'Position', [0,0,1,1],...
                'FontUnits','normalized',...
                'FontSize', 0.5,...
                'String', 'Calibrate CellSens Laser Power Button',...
                'BackgroundColor',[1 0.5 0.5],...
                'Callback', @(src,evnt)set_pos_laser_power_button(this),...
                'Enable','off');
            
            %--------------------------------------------------------------
            uicontrol(...
                'Parent', objPanelLaserAttenuation.hMainPanel,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0,0.5,1,0.5],...
                'String', sprintf('Laser Attenuation [%%]:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',objPanelLaserAttenuation.BackgroundColor,...
                'HorizontalAlignment', 'center');
            this.GUI.hSliderLaserAttenuation = uicontrol(...
                'Parent', objPanelLaserAttenuation.hMainPanel,...
                'Style', 'slider',...
                'Min',0,...
                'Max',100,...
                'SliderStep',[1 10]/100,...
                'Units', 'normalized',...
                'Position', [0,0,0.75,0.5],...
                'Enable','off');
            addlistener(this.GUI.hSliderLaserAttenuation,'ContinuousValueChange',...
                @(src,event)set_laser_attenuation(this,src));
            this.GUI.hEditLaserAttenuation = uicontrol(...
                'Parent', objPanelLaserAttenuation.hMainPanel,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [0.75,0,0.25,0.5],...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Callback', @(src,evnt)set_laser_attenuation(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            uicontrol(...
                'Parent', objPanelZdcSearchRange.hMainPanel,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0,0.5,1,0.5],...
                'String', sprintf('Focus Search Range [µm]:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',objPanelZdcSearchRange.BackgroundColor,...
                'HorizontalAlignment', 'center');
            this.GUI.hSliderZdcSearchRange = uicontrol(...
                'Parent', objPanelZdcSearchRange.hMainPanel,...
                'Style', 'slider',...
                'Min',0,...
                'Max',1000,...
                'SliderStep',[10 100]/1000,...
                'Units', 'normalized',...
                'Position', [0,0,0.75,0.5],...
                'Enable','off');
            addlistener(this.GUI.hSliderZdcSearchRange,'ContinuousValueChange',...
                @(src,event)set_zdc_search_range(this,src));
            this.GUI.hEditZdcSearchRange = uicontrol(...
                'Parent', objPanelZdcSearchRange.hMainPanel,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [0.75,0,0.25,0.5],...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Callback', @(src,evnt)set_zdc_search_range(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            uicontrol(...
                'Parent', objPanelZdcOffset.hMainPanel,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0,0.5,1,0.5],...
                'String', sprintf('Offset [AU]:'),...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Backgroundcolor',objPanelZdcOffset.BackgroundColor,...
                'HorizontalAlignment', 'center');
            this.GUI.hSliderZdcOffset = uicontrol(...
                'Parent', objPanelZdcOffset.hMainPanel,...
                'Style', 'slider',...
                'Min',0,...
                'Max',2080,...
                'SliderStep',[10 100]/2080,...
                'Units', 'normalized',...
                'Position', [0,0,0.75,0.5],...
                'Enable','off');
            addlistener(this.GUI.hSliderZdcOffset,'ContinuousValueChange',...
                @(src,event)set_zdc_offset(this,src));
            this.GUI.hEditZdcOffset = uicontrol(...
                'Parent', objPanelZdcOffset.hMainPanel,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [0.75,0,0.25,0.5],...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'Callback', @(src,evnt)set_zdc_offset(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            this.GUI.hToggleActZdc = uicontrol(...
                'Parent',objPanelZdcLock.hMainPanel,...
                'Style', 'togglebutton',...
                'Units','normalized',...
                'Position', [0,0,1,1],...
                'FontUnits','normalized',...
                'FontSize', 0.5,...
                'String', 'Activate Auto-Focus',...
                'BackgroundColor',[1 0.5 0.5],...
                'Callback', @(src,evnt)set_zdc_state(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            this.GUI.hPushStartScan = uicontrol(...
                'Parent',objPanelScan.hMainPanel,...
                'Style', 'pushbutton',...
                'Units','normalized',...
                'Position', [0,0,1,1],...
                'FontUnits','normalized',...
                'FontSize', 0.5,...
                'String', 'Scan Coverslide',...
                'Callback', @(src,evnt)scan_coverslide(this,src),...
                'Enable','off');
            
            %--------------------------------------------------------------
            
            hPanel = uipanel(...
                'Parent', this.hFig,...
                'Units','normalized',...
                'backgroundcolor','w',...
                'Position',[2/3 0 1/3 0.05]);
            
            this.BAR.hAx = axes(...
                'Parent',hPanel,...
                'Units','normalized',...
                'Position', [0 0 1 1],...
                'TickLength',[0 0],...
                'Box','on',...
                'XTickLabel','off',...
                'YTickLabel','off');
            
            this.BAR.hPatch = patch(...
                'xdata',[0 0 0 0],...
                'ydata',[0 0 1 1],...
                'facecolor','r');
            
            this.BAR.hText = text(0.01,0.5,'',...
                'FontUnits','normalized',...
                'FontSize',0.7);
            
            axis(this.BAR.hAx,[0 1 0 1])
            
            %%
            hToolbar = uitoolbar(...
                'Parent',this.hFig);
            
            this.NAVI.hZoom = zoom(this.hFig);
            this.NAVI.hZoom.ActionPostCallback = @(src,evnt)sync_ROI(this,src,evnt);
            uitoggletool(...
                'Parent', hToolbar,...
                'Tag','Zoom',...
                'TooltipString','Zoom',...
                'CData', reshape([NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN 0 0 0 0 0 0 NaN 0 0 0 0 0 NaN 0 NaN NaN 0 0 1 1 0 0 NaN NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 1 1 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN 0 0 0 0 0 0 NaN 0 0 0 0 0 NaN 0 NaN NaN 0 0 1 1 0 0 NaN NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 1 1 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN 0 0 0 0 0 0 NaN 0 0 0 0 0 NaN 0 NaN NaN 0 0 1 1 0 0 NaN NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 1 1 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0.500000000000000 NaN NaN NaN NaN],[16 16 3]),...
                'ClickedCallback', @(src,evnt)set_zoom(this,src));
            
            this.NAVI.hPan = pan(this.hFig);
            this.NAVI.hPan.ActionPostCallback = @(src,evnt)sync_ROI(this,src,evnt);
            uitoggletool(...
                'Parent', hToolbar,...
                'Tag','Pan',...
                'TooltipString','Pan',...
                'CData', reshape([NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN],[16 16 3]),...
                'ClickedCallback', @(src,evnt)set_pan(this,src));
            uipushtool(...
                'Parent', hToolbar,...
                'TooltipString','Save Results',...
                'CData', reshape([NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 NaN 0 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN 0 0 0 0 0 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0 0.190000000000000 0.0400000000000000 0.310000000000000 NaN 0 NaN 0 NaN NaN 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0 0.190000000000000 0.0400000000000000 0.310000000000000 NaN 0 0 0 0 0 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0.930000000000000 0.510000000000000 0.0400000000000000 0.310000000000000 NaN NaN NaN NaN NaN NaN 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0.930000000000000 0.510000000000000 0.0400000000000000 0.310000000000000 NaN 0 NaN NaN NaN NaN 0 0.0400000000000000 0.0400000000000000 0.0400000000000000 0.0400000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN 0 0 0 0 0 0 0.630000000000000 0 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN 0 NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0.310000000000000 0.310000000000000 NaN NaN NaN NaN NaN NaN NaN 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 NaN 0 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN 0 0 0 0 0 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0 0.190000000000000 0.0400000000000000 0.310000000000000 NaN 0 NaN 0 NaN NaN 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0 0.190000000000000 0.0400000000000000 0.310000000000000 NaN 0 0 0 0 0 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0.930000000000000 0.510000000000000 0.0400000000000000 0.310000000000000 NaN NaN NaN NaN NaN NaN 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0.930000000000000 0.510000000000000 0.0400000000000000 0.310000000000000 NaN 0 NaN NaN NaN NaN 0 0.0400000000000000 0.0400000000000000 0.0400000000000000 0.0400000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN 0 0 0 0 0 0 0.630000000000000 0 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN 0 NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0.310000000000000 0.310000000000000 NaN NaN NaN NaN NaN NaN NaN 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 NaN 0 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN 0 0 0 0 0 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0 0.190000000000000 0.0400000000000000 0.310000000000000 NaN 0 NaN 0 NaN NaN 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0 0.190000000000000 0.0400000000000000 0.310000000000000 NaN 0 0 0 0 0 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0.930000000000000 0.510000000000000 0.0400000000000000 0.310000000000000 NaN NaN NaN NaN NaN NaN 0 0.950000000000000 0.950000000000000 0.950000000000000 0 0.630000000000000 0.930000000000000 0.510000000000000 0.0400000000000000 0.310000000000000 NaN 0 NaN NaN NaN NaN 0 0.0400000000000000 0.0400000000000000 0.0400000000000000 0.0400000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN 0 0 0 0 0 0 0.630000000000000 0 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.630000000000000 0.0400000000000000 0.310000000000000 NaN 0 NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0.310000000000000 0.310000000000000 NaN NaN NaN NaN NaN NaN NaN 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 0.310000000000000 NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0],[16 16 3]),...
                'Separator','on',...
                'ClickedCallback',@(src,evnt)save_results(this));
            uipushtool(...
                'Parent', hToolbar,...
                'TooltipString','Open Documentation',...
                'CData', reshape([NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN],[16 16 3]),...
                'Separator','on');
            
            %%
            set(this.hFig,'Visible','on',...
                'Position',figPos)
        end %fun
        function load_profile(this)
            [fileName,filePath,ext] = uigetfile(...
                '.cfg','Load µManager Profile',this.WorkPath);
            if not(ext)
                return
            end %if
            
            set(this.GUI.hEditProfile,...
                'String',fullfile(filePath,[fileName,ext]))
        end %fun
        
        %% getter
        function x = get_img_size(this)
            ROI = get_camera_ROI(this.MICMAN); %[i0,j0,w,h]
            x = unique(ROI(3:4));
            if numel(x) > 1
                %image width and height not equal
            end %if
        end %fun
        %         function x = get_exp_time(this)
        %             x = get_exposure_time(this.MICMAN); %[ms]
        %         end %fun
        
        function x = get_acq_mode(this)
            option = get(this.GUI.hDropAcqMode,'String');
            selection = get(this.GUI.hDropAcqMode,'Value');
            x = option{selection};
        end %fun
        
        function [ovHeight,ovWidth] = get_overview_size(this,unit)
            imgSize = get_img_size(this);
            
            ovHeight = this.Acq.ScanSize*imgSize; %[px]
            ovWidth = this.Acq.ScanSize*imgSize; %[px]
            
            if strcmp(unit,'µm')
                pxSize = get_img_px_size(this.MICMAN);

                ovHeight = ovHeight*pxSize; %[µm]
                ovWidth = ovWidth*pxSize; %[µm]
            end %if
        end %fun
        
        function dic_scan = get_dic_scan_img(this)
           dic_scan = this.Acq.imgOV;
        end
        function get_dic_bg(this)
            set_filter_revolver_position(this.MICMAN,5)
                    set_cleanup_filter_set(this.MICMAN.CleanupFilter,5) %remove any cleanup filter
                    set_transmission_lamp_shutter_state(this.MICMAN,1)
                    
                    %%                    
                    this.Acq.ImgDicBg = snap_img(this.MICMAN);
                    
                    set(this.GUI.hImgDicBg,...
                        'cdata',this.Acq.ImgDicBg)
                    
                    %%
                    set_transmission_lamp_shutter_state(this.MICMAN,0)
        end %fun
        
        %% setter
        function set_img_size(this,x)
            if ishandle(x)
                switch get(x,'Style')
                    case 'slider'
                        x = get(x,'Value');
                    case 'edit'
                        x = str2double(get(x,'String'));
                end %switch
            end %if
            x = round(x);
            
            if mod(x,2) %check if odd
                x = x + 1; %make it even
            end %if
            
            %%
            %             if get_img_size(this) ~= x
            x0 = (2048-x)/2;
            set_camera_ROI(this.MICMAN,[x0 x0 x x])
            
            set(this.GUI.hEditImgSize,'String',x)
            set(this.GUI.hSliderImgSize,'Value',x)
            
            %%
            update_cam_illu_area(this)
            update_scan_path(this)
            %             end %if
        end %fun
        function set_scan_size(this,x)
            if ishandle(x)
                switch get(x,'Style')
                    case 'slider'
                        x = get(x,'Value');
                    case 'edit'
                        x = str2double(get(x,'String'));
                end %switch
            end %if
            x = round(x);
            
            %%
            if this.Acq.ScanSize ~= x
                this.Acq.ScanSize = x;
                
                set(this.GUI.hEditScanSize,'String',x)
                set(this.GUI.hSliderScanSize,'Value',x)
                
                %%
                initialize_overview_scan(this)
                update_scan_path(this)
            end %if
        end %fun
        
        function set_exp_time(this,x)
            if ishandle(x)
                switch get(x,'Style')
                    case 'slider'
                        x = get(x,'Value');
                    case 'edit'
                        x = str2double(get(x,'String'));
                end %switch
            end %if
            x = round(x);
            
            %%
            if get_exposure_time(this.MICMAN) ~= x
                set_exposure_time(this.MICMAN,x) %[ms]
                
                set(this.GUI.hEditExpTime,'String',x)
                set(this.GUI.hSliderExpTime,'Value',x)
            end %if
        end %fun
        
        function set_dic_lamp_voltage(this,x)
            if ishandle(x)
                switch get(x,'Style')
                    case 'slider'
                        x = get(x,'Value');
                    case 'edit'
                        x = str2double(get(x,'String'));
                end %switch
            end %if
            
            %%
            %             if get_transmission_lamp_voltage(this.MICMAN) ~= x
            set_transmission_lamp_voltage(this.MICMAN,x) %[ms]
            
            set(this.GUI.hEditLampVoltage,'String',x)
            set(this.GUI.hSliderLampVoltage,'Value',x)
            %             end %if
        end %fun
        
        function set_zdc_search_range(this,x)
            if ishandle(x)
                switch get(x,'Style')
                    case 'slider'
                        x = get(x,'Value');
                    case 'edit'
                        x = str2double(get(x,'String'));
                end %switch
            end %if
            
            %%
            %             if get_auto_focus_search_range(this.MICMAN) ~= x
            set_auto_focus_search_range(this.MICMAN,x) %[ms]
            
            set(this.GUI.hEditZdcSearchRange,'String',x)
            set(this.GUI.hSliderZdcSearchRange,'Value',x)
            %             end %if
        end %fun
        function set_zdc_offset(this,x)
            if ishandle(x)
                switch get(x,'Style')
                    case 'slider'
                        x = get(x,'Value');
                    case 'edit'
                        x = str2double(get(x,'String'));
                end %switch
            end %if
            
            %%
            %             if get_auto_focus_offset(this.MICMAN) ~= x
            set_auto_focus_offset(this.MICMAN,x) %[ms]
            
            set(this.GUI.hEditZdcOffset,'String',x)
            set(this.GUI.hSliderZdcOffset,'Value',x)
            %             end %if
        end %fun
        function set_zdc_state(this,x)
            if ishandle(x)
                x = get(x,'Value');
            end %if
            
            if x == 1 %switch ZDC auto-focus on
                scan_and_lock_into_auto_focus(this.MICMAN)
            
                if get_auto_focus_state(this.MICMAN)
                    set(this.GUI.hToggleActZdc,...
                        'BackgroundColor',[0.5 1 0.5])
                else %ZDC auto-focus not estabished successfully
                    set(this.GUI.hToggleActZdc,...
                        'Value',0,...
                        'BackgroundColor',[1 0.5 0.5])
                end %if
            else %switch ZDC auto-focus off
                set_auto_focus_state(this.MICMAN,0)
                
                set(this.GUI.hToggleActZdc,...
                        'BackgroundColor',[1 0.5 0.5])
            end %if
        end %fun
        
        function set_fluor_laser_line(this,x)
            if ishandle(x)
                option = get(x,'String');
                selection = get(x,'Value');
                x = str2double(option{selection});
            end %if
            
            %%
            %             if this.Acq.LaserWvlnth ~= x
            this.Acq.LaserWvlnth = x;
            set(this.GUI.hToggleLaserPowerButton,...
                'BackgroundColor',[1 0.5 0.5])
            %             end %if
        end %fun
        
        function set_pos_cleanup_filter_button(this)
            update_screen_shot(this.MICMAN.ScreenShot)
            cleanup_filter_dropdown_pos(this.MICMAN.CleanupFilter)
            
            set(this.GUI.hToggleCleanupFilterButton,...
                'BackgroundColor',[0.5 1 0.5])
        end %fun
        
        function set_pos_laser_power_button(this)
            update_screen_shot(this.MICMAN.ScreenShot)
            set_laser_state_toggle_pos(this.MICMAN.Laser,...
                this.Acq.LaserWvlnth)
            
            set(this.GUI.hToggleLaserPowerButton,...
                'BackgroundColor',[0.5 1 0.5])
        end %fun
        
        function set_tab(this,evnt)
            switch get(evnt.NewValue,'Title')
                case 'Live View'
                    start(this.Acq.LiveViewTimer);
                otherwise
                    stop(this.Acq.LiveViewTimer);
            end %switch
        end %for
        
        %% updater
        function update_navi_focus(this,pos)
            set(this.GUI.hAxFocus,...
                'xlim',[pos(1) pos(1)+pos(3)],...
                'ylim',[pos(2) pos(2)+pos(4)])
        end %fun
        
        function update_cam_illu_area(this)
            imgSize = get_img_size(this);
            x0 = (2048-imgSize)/2;
            
            img = false(2048,2048);
            img(x0+1:2048-x0,x0+1:2048-x0) = true;
            
            set(this.GUI.hImgCamIlluArea,...
                'xdata',1:2048,...
                'ydata',1:2048,...
                'cdata',img)
        end %fun
        
        function initialize_overview_scan(this)
            pxSize = get_img_px_size(this.MICMAN);
            [totalHeight,totalWidth] = get_overview_size(this,'µm'); %[µm]
            
            this.Acq.imgOV = uint16(nan(totalHeight/pxSize,totalWidth/pxSize)*2^16);
            
            set(this.GUI.hImgFocus,...
                'xdata',(-totalWidth/2:totalWidth/2),...
                'ydata',(-totalHeight/2:totalHeight/2),...
                'cdata',this.Acq.imgOV)
            set(this.GUI.NAVI.hImg,...
                'xdata',(-totalWidth/2:totalWidth/2),...
                'ydata',(-totalHeight/2:totalHeight/2),...
                'cdata',this.Acq.imgOV)
            
            %%
            fcn = makeConstrainToRectFcn('imrect',...
                [(-totalWidth/2)-0.5,(totalWidth/2)+0.5],...
                [(-totalHeight/2)-0.5,(totalHeight/2)+0.5]);
            setPositionConstraintFcn(this.NAVI.hRoi,fcn);
            setPosition(this.NAVI.hRoi,...
                [(-totalWidth/2)-0.5,(-totalHeight/2)-0.5,...
                totalWidth,totalHeight])
        end %fun
        function update_scan_path(this)
            posStageCtr = get_central_xy_pos(this.MICMAN); %[x0,y0]
            
            [x,y,bad] = set_rectangular_path(this.MICMAN,...
                this.Acq.ScanSize,this.Acq.ScanSize);
            
            set(this.GUI.hLineScanPath,...
                'xdata',x-posStageCtr(1),...
                'ydata',y-posStageCtr(2))
            
            %%
            [totalHeight,totalWidth] = get_overview_size(this,'µm');
            
            set(this.GUI.hAxFocus,...
                'xlim',[-totalWidth/2 totalWidth/2],...
                'ylim',[-totalHeight/2 totalHeight/2])
        end %fun
        
        function scan_overview(this)
            start_live_view(this)
            
            %%
            [x,y,bad] = set_rectangular_path(this.MICMAN,...
                this.Acq.ScanSize,this.Acq.ScanSize);
            [totalHeight,totalWidth] = get_overview_size(this,'px');
            
            for idxPos = 1:sum(not(bad(:)))
                set_xy_pos_micron(this.MICMAN,[x(idxPos) y(idxPos)]) %move stage
                pause(0.1) %delay for the auto-focus to adapt
                
                %%
                img = snap_img(this.MICMAN);
                
                if get(this.GUI.hCheckFlatFieldCorr,'value')
                    img = img - this.Acq.ImgDicBg;
                end %if
                
                [j,i] = scan_center_to_img_idx(...
                    this.MICMAN,x(idxPos),y(idxPos),...
                    this.Acq.ScanSize,this.Acq.ScanSize);
                idx = sub2ind([totalHeight,totalWidth],i(:),j(:));
                
                this.Acq.imgOV(idx) = img(:);
                clim = nanquantile(this.Acq.imgOV,[0.01 0.99]);
                
                set(this.GUI.hImgFocus,...
                    'cdata',this.Acq.imgOV)
                set(this.GUI.NAVI.hImg,...
                    'cdata',this.Acq.imgOV)
                
                set(this.GUI.hAxFocus,'clim',clim)
%                 caxis(this.GUI.hAxFocus,clim)
                caxis(this.GUI.NAVI.hAx,clim)
            end %for
            
            %%
            stop_live_view(this)
        end %fun
                
        function start_live_view(this)
            set([this.GUI.hDropAcqMode,...
                this.GUI.hDropLaserWvlnth,...
                this.GUI.hSliderScanSize,...
                this.GUI.hEditScanSize,...
                this.GUI.hToggleCleanupFilterButton,...
                this.GUI.hToggleLaserPowerButton,...
                this.GUI.hEditLaserAttenuation,...
                this.GUI.hSliderZdcSearchRange,...
                this.GUI.hEditZdcSearchRange],...
                'Enable','off')
            switch get_acq_mode(this)
                case 'DIC'
                    set_filter_revolver_position(this.MICMAN,5)
                    set_cleanup_filter_set(this.MICMAN.CleanupFilter,5) %remove any cleanup filter
                    set_transmission_lamp_shutter_state(this.MICMAN,1)
                case 'Fluorescense'
                    set_filter_revolver_position(this.MICMAN,0)
                    set_cleanup_filter_set(this.MICMAN.CleanupFilter,...
                        this.Acq.LaserWvlnth) %put respective cleanup filter
                    set_laser_state(this.MICMAN.Laser,this.Acq.LaserWvlnth,1); %switch on laser
            end %switch
        end %fun
        function update_live_view(this)
            img = snap_img(this.MICMAN);
            img = norm2quantile(img,[0.05,0.95]);
            [imgHeight,imgWidth] = size(img);
            
            set(this.GUI.hImgLive,...
                'xdata',1:imgWidth,...
                'ydata',1:imgHeight,...
                'cdata',img)
        end %fun
        function stop_live_view(this)
            switch get_acq_mode(this)
                case 'DIC'
                    set_transmission_lamp_shutter_state(this.MICMAN,0)
                case 'Fluorescense'
                    set_laser_state(this.MICMAN.Laser,this.Acq.LaserWvlnth,0); %switch on laser
            end %switch
            set([this.GUI.hDropAcqMode,...
                this.GUI.hDropLaserWvlnth,...
                this.GUI.hSliderScanSize,...
                this.GUI.hEditScanSize,...
                this.GUI.hToggleCleanupFilterButton,...
                this.GUI.hToggleLaserPowerButton,...
                this.GUI.hEditLaserAttenuation,...
                this.GUI.hSliderZdcSearchRange,...
                this.GUI.hEditZdcSearchRange],...
                'Enable','on')
        end %fun
        
        %%
        function set_zoom(this,src)
            switch get(src,'State')
                case 'on'
                    set(this.NAVI.hZoom,'Enable','on')
                case 'off'
                    set(this.NAVI.hZoom,'Enable','off')
            end %fun
        end %fun
        function set_pan(this,src)
            switch get(src,'State')
                case 'on'
                    set(this.NAVI.hPan,'Enable','on')
                case 'off'
                    set(this.NAVI.hPan,'Enable','off')
            end %fun
        end %fun
        
        function sync_ROI(this,~,evd)
            if evd.Axes == this.GUI.RAW.Donor.hAx
                xlim = get(evd.Axes,'xlim');
                ylim = get(evd.Axes,'ylim');
                setPosition(this.NAVI.hRoi,...
                    [xlim(1),ylim(1),xlim(2)-xlim(1),ylim(2)-ylim(1)])
            end %if
        end %fun
        
        function initialize_micro_manager(this,x)
            if ishandle(x)
                x = get(x,'Value');
            end %if
            
            if x == 1
                profile = get(this.GUI.hEditProfile,'String');
                [this.MICMAN.MicManPath,profileName,profileExt] = ...
                    fileparts(profile);
                this.MICMAN.Profile = [profileName profileExt];
                
                initialize_micro_manager(this.MICMAN,'')
                
                %%
                set_img_size(this,get_img_size(this))
                
                set_exp_time(this,get_exposure_time(this.MICMAN))
                
                set_dic_lamp_voltage(this,get_transmission_lamp_voltage(this.MICMAN))
                
                set_zdc_search_range(this,get_auto_focus_search_range(this.MICMAN))
                set_zdc_offset(this,get_auto_focus_offset(this.MICMAN))
                
                set_transmission_lamp_power(this.MICMAN,1) %switch on DIC lamp
                
                %%
                set([this.GUI.hEditProfile,...
                    this.GUI.hPushSwitchProfile],...
                    'Enable','off')
                                
                set([this.GUI.hSliderImgSize,...
                    this.GUI.hEditImgSize,...
                    this.GUI.hSliderScanSize,...
                    this.GUI.hEditScanSize,...
                    this.GUI.hSliderExpTime,...
                    this.GUI.hEditExpTime,...
                    this.GUI.hDropAcqMode,...
                    this.GUI.hSliderLampVoltage,...
                    this.GUI.hEditLampVoltage,...
                    this.GUI.hCheckFlatFieldCorr,...
                    this.GUI.hPushDicBgSample,...
                    this.GUI.hToggleCleanupFilterButton,...
                    this.GUI.hToggleLaserPowerButton,...
                    this.GUI.hEditLaserAttenuation,...
                    this.GUI.hDropLaserWvlnth,...
                    this.GUI.hSliderZdcSearchRange,...
                    this.GUI.hEditZdcSearchRange,...
                    this.GUI.hSliderZdcOffset,...
                    this.GUI.hEditZdcOffset,...
                    this.GUI.hToggleActZdc],...
                    'Enable','on')
                
                set(this.GUI.hToggleInitMM,'BackGroundcolor',[0.5 1 0.5])
            else
                unloadAllDevices(this.MICMAN.CoreAPI)
                
                %%
                set([this.GUI.hEditProfile,...
                    this.GUI.hPushSwitchProfile],...
                    'Enable','on')
                
                set([this.GUI.hSliderImgSize,...
                    this.GUI.hEditImgSize,...
                    this.GUI.hSliderScanSize,...
                    this.GUI.hEditScanSize,...
                    this.GUI.hSliderExpTime,...
                    this.GUI.hEditExpTime,...
                    this.GUI.hDropAcqMode,...
                    this.GUI.hSliderLampVoltage,...
                    this.GUI.hEditLampVoltage,...
                    this.GUI.hCheckFlatFieldCorr,...
                    this.GUI.hPushDicBgSample,...
                    this.GUI.hToggleCleanupFilterButton,...
                    this.GUI.hToggleLaserPowerButton,...
                    this.GUI.hEditLaserAttenuation,...
                    this.GUI.hDropLaserWvlnth,...
                    this.GUI.hSliderZdcSearchRange,...
                    this.GUI.hEditZdcSearchRange,...
                    this.GUI.hSliderZdcOffset,...
                    this.GUI.hEditZdcOffset,...
                    this.GUI.hToggleActZdc],...
                    'Enable','off')
                
                set(this.GUI.hToggleInitMM,'BackGroundcolor',[1 0.5 0.5])
            end %if
        end %fun
        
        %% INFO BAR
        function set_bar_text(this,txt)
            set(this.BAR.hText,'String',txt)
            drawnow nocallbacks
        end %fun
        function set_bar_percentage(this,p)
            set(this.BAR.hPatch,'XData',[0 p p 0])
            drawnow nocallbacks
        end %fun
        
        %%
        function proc_keyboard(this,evnt)
            if isempty(evnt.Modifier)
                switch evnt.Key
                end %switch
            elseif strcmp(evnt.Modifier,'control')
                switch evnt.Key
                    case 'l'
                        load_data(this)
                    case 's'
                        save_results(this)
                end %switch
            end %if
        end %fun
        
        %% analysis
        function eval_DIC_channel( this, wind )
            dic_scan = get_dic_scan_img(this);
%             img_dims = get_img_size(this);
            img_dims = [600, 600];
%             wind = 9;
            [bw_img, cc, stats] = ...
                process_and_label_DIC( dic_scan, img_dims, wind );
            
            
            
            
        end
        
        
    end %methods
end %classdef